version: '3.8'

services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3443/api

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3443:3443"
    volumes:
      - ../server:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/certificate-manager
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ../database/data:/data/db
