# Usage:
# Start MongoDB: docker-compose -f docker-compose.mongodb.yml up
# Start in background: docker-compose -f docker-compose.mongodb.yml up -d
# Stop: docker-compose -f docker-compose.mongodb.yml down
# Remove data volume: docker-compose -f docker-compose.mongodb.yml down --volumes

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local