# How to use:
# Build:        docker compose -f docker-compose.server-db.yml build
# Start:        docker compose -f docker-compose.server-db.yml up
# Stop:         docker compose -f docker-compose.server-db.yml down
# Rebuild:      docker compose -f docker-compose.server-db.yml up --build
# Background:   docker compose -f docker-compose.server-db.yml up -d
# View logs:    docker compose -f docker-compose.server-db.yml logs -f

services:
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3443:3443"
    volumes:
      - ../server:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/certificate-manager
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ../database/data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
