# Usage:
# Build and start: docker-compose -f docker-compose.client.yml up --build
# Start: docker-compose -f docker-compose.client.yml up
# Start in background: docker-compose -f docker-compose.client.yml up -d
# Stop: docker-compose -f docker-compose.client.yml down
# Rebuild: docker-compose -f docker-compose.client.yml build client

services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3443/api
