version: '3.8'

services:
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3443:3443"
    volumes:
      - ../server:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/certificate-manager
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ../database/data:/data/db
